name: VapourCod3r Alpha

run-name: "${{ inputs.AnimeName }} ${{ inputs.EpLabel }} - ${{ inputs.VidRes }} - Q${{ inputs.QScale }}/CPU${{ inputs.EncSpeed }}"

on:
  workflow_dispatch:
    inputs:
      AnimeName:
        description: "AnimeName"
        required: true
        type: choice
        options:
        - "Oshi.no.Ko"
        - "Heavenly.Delusion"
        - "Hells.Paradise.Jigokuraku"
        - "Insomniacs.After.School"
      EpLabel:
        description: "EpLabel, S0[0-9]E[0-9][0-9]"
        required: true
        type: string
        default: "S01E01"
      EncSpeed:
        description: "EncSpeed"
        required: true
        type: choice
        options:
        - "2"
        - "3"
        - "4"
        - "1"
      QScale:
        description: "QScale, 13~46"
        required: true
        type: number
      VidRes:
        description: "VidRes, 576p || 1024x576"  # AR = 16/9
        required: true
        type: string
        default: "576p"
      ForceRecode:
        description: "ForceRecode Previous Chunks"
        required: true
        type: boolean
        default: false
      MergeOnly:
        description: "Only Merge Previously Encoded File"
        required: false
        type: boolean
        default: false

env:
  AnimeName: ${{ github.event.inputs.AnimeName }}
  EpLabel: ${{ github.event.inputs.EpLabel }}
  EncSpeed: ${{ github.event.inputs.EncSpeed }}
  QScale: ${{ github.event.inputs.QScale }}
  VidRes: ${{ github.event.inputs.VidRes }}
  ForceRecode: ${{ github.event.inputs.ForceRecode }}
  MergeOnly: ${{ github.event.inputs.MergeOnly }}
  VapourCod3r_Hash: ${{ secrets.VapourCod3r_ZHash }}
  RCLONE_CONFIG_HASH: ${{ secrets.RCLONE_CONFIG_HASH }}

jobs:
  generator:
    name: "Job Matrix Preparation"
    if: github.event.inputs.MergeOnly != 'true'
    runs-on: ubuntu-22.04

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      artchunk: ${{ steps.set-artmatrix.outputs.artchunk }}
      artmatrix: ${{ steps.set-artmatrix.outputs.artmatrix }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: GitHub Auth
        uses: rokibhasansagar/custom_workflows/git_config@main
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Create EncMatrix
        id: set-matrix
        run: |
          eval 'set -eo pipefail' 2>/dev/null
          eval 'set +o history' 2>/dev/null
          # Get GIST latest Revision number
          export latestRevision=$(curl -sL "https://gist.github.com/rokibhasansagar/${VapourCod3r_Hash}/" | grep "/matrixGen\.sh" | awk -F'/raw/' '{print $2}' | awk -F'/' '{print $1}')
          # Generate Workflow Matrix
          curl -sL "https://gist.github.com/rokibhasansagar/${VapourCod3r_Hash}/raw/${latestRevision}/matrixGen.sh" -O
          source ./matrixGen.sh
          eval 'set -o history' 2>/dev/null
      - name: Get artchunk and artmatrix
        id: set-artmatrix
        run: |
          eval 'set -eo pipefail' 2>/dev/null
          eval 'set +o history' 2>/dev/null
          # Get GIST latest Revision number
          export latestRevision=$(curl -sL "https://gist.github.com/rokibhasansagar/${VapourCod3r_Hash}/" | grep "/matrixGen\.sh" | awk -F'/raw/' '{print $2}' | awk -F'/' '{print $1}')
          # Generate Artifactory Matrix
          curl -sL "https://gist.github.com/rokibhasansagar/${VapourCod3r_Hash}/raw/${latestRevision}/artGen.sh" -O
          source ./artGen.sh
          eval 'set -o history' 2>/dev/null

  uploader:
    name: "Vapour Artifactory"
    if: github.event.inputs.MergeOnly != 'true'
    runs-on: ubuntu-22.04
    needs: generator

    strategy:
      fail-fast: true
      max-parallel: 8
      matrix:
        artnum: ${{fromJson(needs.generator.outputs.artmatrix)}}

    env:
      artnum: ${{ matrix.artnum }}
      artchunk: ${{ needs.generator.outputs.artchunk }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: GitHub Auth
        uses: rokibhasansagar/custom_workflows/git_config@main
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Download Media and Split into Parts
        run: |
          eval 'set -eo pipefail' 2>/dev/null
          eval 'set +o history' 2>/dev/null
          # Get GIST latest Revision number
          export latestRevision=$(curl -sL "https://gist.github.com/rokibhasansagar/${VapourCod3r_Hash}/" | grep "/matrixGen\.sh" | awk -F'/raw/' '{print $2}' | awk -F'/' '{print $1}')
          # Generate Artifactory Matrix
          curl -sL "https://gist.github.com/rokibhasansagar/${VapourCod3r_Hash}/raw/${latestRevision}/splitGen.sh" -O
          source ./splitGen.sh
          eval 'set -o history' 2>/dev/null
      - name: Upload Source Media as Artifact
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: artifact
          path: ~/data/${{env.AnimeName}}.${{env.EpLabel}}.SOURCE.mkv.${{env.artnum}}
          retention-days: 3
      - name: Upload Source Media as Artifact
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ~/data/${{env.AnimeName}}.${{env.EpLabel}}.SOURCE.mkv.${{env.artnum}}
          retention-days: 3

  synthesizer:
    name: "Vapour Synthesizer"
    if: github.event.inputs.MergeOnly != 'true' && ( !cancelled() || success() )
    runs-on: ubuntu-22.04
    needs: [generator, uploader]

    strategy:
      fail-fast: false
      max-parallel: 16
      matrix:
        ChunkID: ${{fromJson(needs.generator.outputs.matrix)}}
    env:
      ChunkID: ${{ matrix.ChunkID }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: GitHub Auth
        uses: rokibhasansagar/custom_workflows/git_config@main
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Download Source Media from Artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: ~/data/artifact/
      - name: VapourCod3r - Chunk ${{env.ChunkID}} from ${{env.AnimeName}} ${{env.EpLabel}}
        run: |
          eval 'set -eo pipefail' 2>/dev/null
          eval 'set +o history' 2>/dev/null
          # Get GIST latest Revision number
          export latestRevision=$(curl -sL "https://gist.github.com/rokibhasansagar/${VapourCod3r_Hash}/" | grep "/vapourGen\.sh" | awk -F'/raw/' '{print $2}' | awk -F'/' '{print $1}')
          # All-in-one Script for VapourCod3r vapourGen
          curl -sL "https://gist.github.com/rokibhasansagar/${VapourCod3r_Hash}/raw/${latestRevision}/vapourGen.sh" -O
          source ./vapourGen.sh
          eval 'set -o history' 2>/dev/null
      - name: VapourCod3r Av1an Error Debugger
        if: failure()
        run: |
          sudo chown -R runner ~/data
          cd ~/data && ls -lA ~/data
          if [[ -s ~/data/enclog.log ]]; then
            tar -I'zstd --ultra -22 -T2' -cf ${ChunkID}.enclog.tzst ~/data/enclog.log 2>/dev/null
            DebugLog=$(curl -fsSL --retry 5 --retry-connrefused --retry-delay 2 --upload-file ${ChunkID}.enclog.tzst https://transfer.sh/ 2>/dev/null)
            if [[ -z ${DebugLog} && ${DebugLog} == '' ]]; then
              DebugLog=$(curl -fsSL --retry 5 --retry-connrefused --retry-delay 2 -T ${ChunkID}.enclog.tzst temp.sh https://temp.sh/ 2>/dev/null)
            fi
            echo -e "See the Failed Encode Log at ${DebugLog}"
          else
            echo -e "The Job broke down before Encode had started"
            exit 1
          fi
      - name: Upload Av1an Log as Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: |
            ~/data/enclog.log
            ~/data/av1temp
          name: enclog.${{env.ChunkID}}
          retention-days: 1

  merger:
    name: "Synthesized Video Joiner"
    if: ( github.event.inputs.MergeOnly == 'true' && !cancelled() ) || success()
    runs-on: ubuntu-22.04
    needs: [generator, synthesizer]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: GitHub Auth
        uses: rokibhasansagar/custom_workflows/git_config@main
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Joiner for VapourCod3d ${{env.AnimeName}} ${{env.EpLabel}}
        run: |
          eval 'set -eo pipefail' 2>/dev/null
          eval 'set +o history' 2>/dev/null
          # Get GIST latest Revision number
          export latestRevision=$(curl -sL "https://gist.github.com/rokibhasansagar/${VapourCod3r_Hash}/" | grep "/xJoiner\.sh" | awk -F'/raw/' '{print $2}' | awk -F'/' '{print $1}')
          # VapourCod3r xJoiner for Final Encoded Video
          curl -sL "https://gist.github.com/rokibhasansagar/${VapourCod3r_Hash}/raw/${latestRevision}/xJoiner.sh" -O
          source ./xJoiner.sh
          eval 'set -o history' 2>/dev/null

